# Generated by rust2rpm 16
%bcond_without check
%global debug_package %{nil}

%global crate capnp

Name:           rust-%{crate}
Version:        0.13.6
Release:        1%{?dist}
Summary:        Runtime library for Cap'n Proto data encoding

# Upstream license specification: MIT
# https://github.com/capnproto/capnproto-rust/issues/224
License:        MIT
URL:            https://crates.io/crates/capnp
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Runtime library for Cap'n Proto data encoding.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md CHANGELOG.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+quickcheck-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+quickcheck-devel %{_description}

This package contains library source intended for building other packages
which use "quickcheck" feature of "%{crate}" crate.

%files       -n %{name}+quickcheck-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+rpc_try-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rpc_try-devel %{_description}

This package contains library source intended for building other packages
which use "rpc_try" feature of "%{crate}" crate.

%files       -n %{name}+rpc_try-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages
which use "std" feature of "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+unaligned-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unaligned-devel %{_description}

This package contains library source intended for building other packages
which use "unaligned" feature of "%{crate}" crate.

%files       -n %{name}+unaligned-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Apr 08 2021 Fabio Valentini <decathorpe@gmail.com> - 0.13.6-1
- Initial package
